services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    RichCongress\Bundle\UnitBundle\Command\DebugFixturesCommand: ~
    RichCongress\Bundle\UnitBundle\Utility\OverrideServicesUtility: ~

    RichCongress\Bundle\UnitBundle\Utility\FixturesManager:
        $databaseToolCollection: '@liip_test_fixtures.services.database_tool_collection'
