services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    RichCongress\Bundle\UnitBundle\Command\DebugFixturesCommand: ~
    RichCongress\Bundle\UnitBundle\Command\DebugOverridenServicesCommand: ~
    RichCongress\Bundle\UnitBundle\Utility\OverrideServicesUtility: ~

    RichCongress\Bundle\UnitBundle\DataFixture\SqliteDatabaseBackup:
        arguments:
            $sqliteDatabaseBackup: '@liip_test_fixtures.services_database_backup.sqlite'

    RichCongress\Bundle\UnitBundle\Utility\FixturesManager:
        arguments:
            $databaseToolCollection: '@liip_test_fixtures.services.database_tool_collection'

    rich_congress_unit.doctrine.dbal.connection_factory:
        class: RichCongress\Bundle\UnitBundle\Doctrine\TestConnectionFactory
        decorates: dama.doctrine.dbal.connection_factory
        arguments:
            $decoratedFactory: '@rich_congress_unit.doctrine.dbal.connection_factory.inner'
